// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMzDuyCrg-bfbBaXMekfCHZrfpsMbR8i8',
    appId: '1:941188217753:web:b358e806310193dc5d3108',
    messagingSenderId: '941188217753',
    projectId: 'splitify-1926b',
    authDomain: 'splitify-1926b.firebaseapp.com',
    storageBucket: 'splitify-1926b.firebasestorage.app',
    measurementId: 'G-4KZ0X9DHW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf6UNIfiTBE-uh4UI55msyQC6jnIRWbBc',
    appId: '1:941188217753:android:93663f776ce061e75d3108',
    messagingSenderId: '941188217753',
    projectId: 'splitify-1926b',
    storageBucket: 'splitify-1926b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjP6WoMhwa4m4xMd4caAKL6AIdV8OrHqU',
    appId: '1:941188217753:ios:eb4ef8bf282f8cd25d3108',
    messagingSenderId: '941188217753',
    projectId: 'splitify-1926b',
    storageBucket: 'splitify-1926b.firebasestorage.app',
    iosBundleId: 'com.splitify.splitify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjP6WoMhwa4m4xMd4caAKL6AIdV8OrHqU',
    appId: '1:941188217753:ios:eb4ef8bf282f8cd25d3108',
    messagingSenderId: '941188217753',
    projectId: 'splitify-1926b',
    storageBucket: 'splitify-1926b.firebasestorage.app',
    iosBundleId: 'com.splitify.splitify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMzDuyCrg-bfbBaXMekfCHZrfpsMbR8i8',
    appId: '1:941188217753:web:fa8e7916fe78e2545d3108',
    messagingSenderId: '941188217753',
    projectId: 'splitify-1926b',
    authDomain: 'splitify-1926b.firebaseapp.com',
    storageBucket: 'splitify-1926b.firebasestorage.app',
    measurementId: 'G-9QGK9YRS7L',
  );
}
